name: app_qstocker
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.0.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.17.5
  firebase_database: ^10.4.5
  cached_network_image: ^3.2.3
  qr_flutter: ^4.0.0 
  http: 1.3.0
  flutterfire_cli: ^0.1.1+2 
  google_fonts: ^6.1.0
  animate_do: ^3.0.2 # pour les animations
  image_picker: ^0.8.7+3
  flutter_localizations: 
    sdk: flutter 
  intl: ^0.19.0   
  curved_navigation_bar: 1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - images/

