// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETwPp4E8vIyaKrUdXMGCeRJLnVL87MV0',
    appId: '1:1015343581305:web:767d3d4679b2cfab5faca8',
    messagingSenderId: '1015343581305',
    projectId: 'qstocker-9b450',
    authDomain: 'qstocker-9b450.firebaseapp.com',
    databaseURL: 'https://qstocker-9b450-default-rtdb.firebaseio.com',
    storageBucket: 'qstocker-9b450.firebasestorage.app',
    measurementId: 'G-R0PK2B0LPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH34169zrMPgPVscRfwSy1ACDXXJFSjog',
    appId: '1:1015343581305:android:eadb2f001d7240f65faca8',
    messagingSenderId: '1015343581305',
    projectId: 'qstocker-9b450',
    databaseURL: 'https://qstocker-9b450-default-rtdb.firebaseio.com',
    storageBucket: 'qstocker-9b450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAl14HoopbpInOX5umQvv6q2hFySzk0Y',
    appId: '1:1015343581305:ios:5b30a8292ffc562e5faca8',
    messagingSenderId: '1015343581305',
    projectId: 'qstocker-9b450',
    databaseURL: 'https://qstocker-9b450-default-rtdb.firebaseio.com',
    storageBucket: 'qstocker-9b450.firebasestorage.app',
    iosClientId: '1015343581305-9sgoe23q40brd42e0e2vi34mb1ah77d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQstocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAl14HoopbpInOX5umQvv6q2hFySzk0Y',
    appId: '1:1015343581305:ios:5b30a8292ffc562e5faca8',
    messagingSenderId: '1015343581305',
    projectId: 'qstocker-9b450',
    databaseURL: 'https://qstocker-9b450-default-rtdb.firebaseio.com',
    storageBucket: 'qstocker-9b450.firebasestorage.app',
    iosClientId: '1015343581305-9sgoe23q40brd42e0e2vi34mb1ah77d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQstocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBETwPp4E8vIyaKrUdXMGCeRJLnVL87MV0',
    appId: '1:1015343581305:web:66ed6c198bc6264f5faca8',
    messagingSenderId: '1015343581305',
    projectId: 'qstocker-9b450',
    authDomain: 'qstocker-9b450.firebaseapp.com',
    databaseURL: 'https://qstocker-9b450-default-rtdb.firebaseio.com',
    storageBucket: 'qstocker-9b450.firebasestorage.app',
    measurementId: 'G-TBHH34KBQR',
  );
}
