// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeyTJuQZLjD-kU_Dd3U00sfIJFS0uHEVY',
    appId: '1:306373090701:web:3aba66cfe540c4915631c4',
    messagingSenderId: '306373090701',
    projectId: 'qstockerpfe',
    authDomain: 'qstockerpfe.firebaseapp.com',
    databaseURL: 'https://qstockerpfe-default-rtdb.firebaseio.com',
    storageBucket: 'qstockerpfe.firebasestorage.app',
    measurementId: 'G-4K10FQ47QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1J0oPRfD0VY0-jc3ygjwJQBW2Xsnajeg',
    appId: '1:306373090701:android:4df3fb9417d73f8c5631c4',
    messagingSenderId: '306373090701',
    projectId: 'qstockerpfe',
    databaseURL: 'https://qstockerpfe-default-rtdb.firebaseio.com',
    storageBucket: 'qstockerpfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYzCsx0qO8YCh9_CxBocyew3aoPSGjEfE',
    appId: '1:306373090701:ios:90aa218620b97f295631c4',
    messagingSenderId: '306373090701',
    projectId: 'qstockerpfe',
    databaseURL: 'https://qstockerpfe-default-rtdb.firebaseio.com',
    storageBucket: 'qstockerpfe.firebasestorage.app',
    iosClientId: '306373090701-f912lm9b957klupsdmf2637sugl0q80t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQstocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYzCsx0qO8YCh9_CxBocyew3aoPSGjEfE',
    appId: '1:306373090701:ios:90aa218620b97f295631c4',
    messagingSenderId: '306373090701',
    projectId: 'qstockerpfe',
    databaseURL: 'https://qstockerpfe-default-rtdb.firebaseio.com',
    storageBucket: 'qstockerpfe.firebasestorage.app',
    iosClientId: '306373090701-f912lm9b957klupsdmf2637sugl0q80t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQstocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeyTJuQZLjD-kU_Dd3U00sfIJFS0uHEVY',
    appId: '1:306373090701:web:8375de32de3932f05631c4',
    messagingSenderId: '306373090701',
    projectId: 'qstockerpfe',
    authDomain: 'qstockerpfe.firebaseapp.com',
    databaseURL: 'https://qstockerpfe-default-rtdb.firebaseio.com',
    storageBucket: 'qstockerpfe.firebasestorage.app',
    measurementId: 'G-48PQ0KJ48B',
  );
}
